# Generated by Django 5.2.6 on 2025-10-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcardtype',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
    ]
