# Generated by Django 5.2.6 on 2025-10-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcardtype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
