# Generated by Django 5.2.6 on 2025-10-21 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_giftcardtype_exchange_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GiftCard',
        ),
        migrations.DeleteModel(
            name='GiftCardType',
        ),
    ]
