# Generated by Django 5.2.6 on 2025-11-17 22:15

import django.db.models.deletion
import django.utils.timezone
import main.models.account
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_number', models.CharField(default=main.models.account.generate_account_number, editable=False, max_length=11, unique=True)),
                ('balance', models.DecimalField(decimal_places=18, default=0, max_digits=40)),
                ('currency', models.CharField(choices=[('GHS', 'Ghana Cedi'), ('USD', 'US Dollar'), ('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('XRP', 'Ripple'), ('LTC', 'Litecoin')], default='USD', max_length=3)),
                ('limit_per_transaction', models.DecimalField(decimal_places=18, default=Decimal('2000'), max_digits=40)),
                ('daily_transfer_limit', models.DecimalField(decimal_places=18, default=Decimal('5000'), max_digits=40)),
                ('monthly_transfer_limit', models.DecimalField(decimal_places=18, default=Decimal('50000'), max_digits=40)),
                ('transfer_allowed', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_role', models.CharField(choices=[('asset', 'Asset'), ('user', 'User (Liability)'), ('revenue', 'Revenue'), ('expenses', 'Expenses'), ('suspense', 'Suspense')], default='user', max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.account')),
                ('wallet', models.CharField(max_length=255)),
                ('blockchain_network', models.CharField(max_length=100)),
            ],
            bases=('main.account',),
        ),
        migrations.CreateModel(
            name='FiatAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.account')),
            ],
            bases=('main.account',),
        ),
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('reference_id', models.CharField(default=main.models.account.generate_reference_number, editable=False, max_length=11, unique=True)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('adjustment', 'Adjustment'), ('fee', 'Fee'), ('credit', 'Internal Credit'), ('debit', 'Internal Debit')], max_length=20)),
                ('direction', models.CharField(blank=True, choices=[('bank_to_account', 'Bank to Account'), ('account_to_bank', 'Account to Bank'), ('account_to_mobile_money', 'Account to Mobile Money'), ('mobile_money_to_account', 'Mobile Money to Account'), ('wallet_to_wallet', 'Wallet to Wallet'), ('fiat_to_crypto', 'Fiat to Crypto'), ('crypto_to_fiat', 'Crypto to Fiat'), ('crypto_swap', 'Crypto Swap'), ('gift_card_to_account', 'Gift Card to Account')], max_length=30, null=True)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('fee', models.DecimalField(decimal_places=18, default=0, max_digits=40)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('GHS', 'Ghana Cedi'), ('USD', 'US Dollar'), ('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('XRP', 'Ripple'), ('LTC', 'Litecoin')], max_length=3)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='main.account')),
                ('destination_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to='main.account')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='main.account')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='main.accounttransaction')),
            ],
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['owner'], name='main_accoun_owner_i_63ba14_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['currency'], name='main_accoun_currenc_0f50f6_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['is_active'], name='main_accoun_is_acti_d5790a_idx'),
        ),
        migrations.AddIndex(
            model_name='accounttransaction',
            index=models.Index(fields=['reference_id'], name='main_accoun_referen_d7eef7_idx'),
        ),
    ]
