# Generated by Django 5.2.6 on 2025-10-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttransaction',
            name='direction',
            field=models.CharField(blank=True, choices=[('bank_to_account', 'Bank to Account'), ('account_to_bank', 'Account to Bank'), ('account_to_mobile_money', 'Account to Mobile Money'), ('mobile_money_to_account', 'Mobile Money to Account'), ('wallet_to_wallet', 'Wallet to Wallet'), ('fiat_to_crypto', 'Fiat to Crypto'), ('crypto_to_fiat', 'Crypto to Fiat'), ('crypto_swap', 'Crypto Swap')], max_length=30, null=True),
        ),
    ]
