# Generated by Django 5.2.6 on 2025-10-23 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_accounttransaction_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttransaction',
            name='currency',
            field=models.CharField(choices=[('GHS', 'Ghana Cedi'), ('USD', 'US Dollar'), ('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('XRP', 'Ripple'), ('LTC', 'Litecoin')], default='USD', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('GHS', 'Ghana Cedi'), ('USD', 'US Dollar'), ('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('XRP', 'Ripple'), ('LTC', 'Litecoin')], default='USD', max_length=3),
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('currency', models.CharField(choices=[('GHS', 'Ghana Cedi'), ('USD', 'US Dollar'), ('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('XRP', 'Ripple'), ('LTC', 'Litecoin')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='main.account')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='main.accounttransaction')),
            ],
        ),
    ]
