# Generated by Django 5.2.6 on 2025-10-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_accounttransaction_currency_alter_account_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransaction',
            name='amount',
            field=models.DecimalField(decimal_places=18, max_digits=40),
        ),
        migrations.AlterField(
            model_name='accounttransaction',
            name='fee',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='amount',
            field=models.DecimalField(decimal_places=18, max_digits=40),
        ),
    ]
