# Generated by Django 5.2.6 on 2025-10-23 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_accounttransaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransaction',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='main.account'),
        ),
    ]
