# Generated by Django 5.2.6 on 2025-10-26 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_accounttransaction_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='currency',
        ),
    ]
