# Generated by Django 5.2.6 on 2025-10-27 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_ledger_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_role',
            field=models.CharField(choices=[('asset', 'Asset'), ('user', 'User (Liability)'), ('revenue', 'Revenue'), ('expenses', 'Expenses')], default='user', max_length=10),
        ),
    ]
