# Generated by Django 5.2.6 on 2025-10-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_account_account_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('adjustment', 'Adjustment'), ('fee', 'Fee')], max_length=20),
        ),
    ]
