# Generated by Django 5.2.6 on 2025-10-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_accounttransaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_role',
            field=models.CharField(choices=[('asset', 'Asset'), ('user', 'User (Liability)'), ('revenue', 'Revenue'), ('expenses', 'Expenses'), ('suspense', 'Suspense')], default='user', max_length=10),
        ),
    ]
