# Generated by Django 5.2.6 on 2025-10-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_account_account_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
