# Generated by Django 5.2.6 on 2025-10-30 23:33

import main.models.account
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_accounttransaction_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounttransaction',
            name='external_party_details',
        ),
        migrations.AddField(
            model_name='accounttransaction',
            name='reference_id',
            field=models.CharField(default=main.models.account.generate_account_number, editable=False, max_length=11, unique=True),
        ),
        migrations.AddIndex(
            model_name='accounttransaction',
            index=models.Index(fields=['reference_id'], name='main_accoun_referen_d7eef7_idx'),
        ),
    ]
