# Generated by Django 5.2.6 on 2025-10-31 01:53

import main.models.account
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_accounttransaction_external_party_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransaction',
            name='reference_id',
            field=models.CharField(default=main.models.account.generate_reference_number, editable=False, max_length=11, unique=True),
        ),
    ]
