# Generated by Django 5.2.6 on 2025-09-24 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_rename_is_verified_user_email_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='otp_token',
            new_name='email_otp',
        ),
    ]
