# Generated by Django 5.2.6 on 2025-09-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_rename_otp_token_user_email_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='expires_at',
        ),
        migrations.AddField(
            model_name='otp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
