# Generated by Django 5.2.6 on 2025-10-25 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0006_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='transfer_allowed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='transfer_limit',
        ),
    ]
