# Generated by Django 5.2.6 on 2025-10-27 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0007_remove_user_balance_remove_user_transfer_allowed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('sys', 'System'), ('manager', 'Manager')], default='user'),
        ),
    ]
