# Generated by Django 5.2.6 on 2025-10-21 19:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCardType',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('desc', models.CharField(max_length=255)),
                ('denominations', models.JSONField(default=list)),
                ('category', models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('FASHION', 'Fashion'), ('GROCERY', 'Grocery'), ('TRAVEL', 'Travel'), ('ENTERTAINMENT', 'Entertainment'), ('HEALTH', 'Health & Wellness'), ('FOOD', 'Food & Dining'), ('HOME', 'Home & Living'), ('SPORTS', 'Sports & Outdoors'), ('BEAUTY', 'Beauty & Personal Care'), ('E-COMMERCE', 'E-commerce')])),
                ('exchange_rate', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_redeemed', models.BooleanField(default=False)),
                ('redeemed_by', models.EmailField(blank=True, max_length=254, null=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('giftcard_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giftcards', to='giftcards.giftcardtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RedeemedGiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('redeemed_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('redeemed', 'Redeemed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('giftcard_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redeemed_giftcards', to='giftcards.giftcardtype')),
                ('redeemed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_giftcards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
