# Generated by Django 5.2.6 on 2025-10-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcards', '0002_alter_redeemedgiftcard_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redeemedgiftcard',
            old_name='amount',
            new_name='amount_claimed',
        ),
        migrations.AddField(
            model_name='redeemedgiftcard',
            name='amount_confirmed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
