# Generated by Django 5.2.6 on 2025-10-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcards', '0003_rename_amount_redeemedgiftcard_amount_claimed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeemedgiftcard',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
